#Kotlin
kotlin.code.style=official
kotlin.daemon.jvmargs=-Xmx3072M

#Gradle
org.gradle.jvmargs=-Xmx4096M -Dfile.encoding=UTF-8
org.gradle.configuration-cache=true
org.gradle.caching=true
# This property tells Gradle which JDK to use for its processes.
# We are pointing it to the JDK bundled with Android Studio to fix an
# incompatibility with the system's default Java version (25).
org.gradle.java.home=/Applications/Android Studio.app/Contents/jbr/Contents/Home

#Android
android.nonTransitiveRClass=true
android.useAndroidX=true